# Generated by Django 5.2.5 on 2026-08-20 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent_pitch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='body_html',
            field=models.TextField(blank=True, default='', help_text='Snapshot of the HTML sent in this campaign.'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='template',
            field=models.ForeignKey(blank=True, help_text='The email template this campaign was sent from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='ai_agent_pitch.emailtemplate'),
        ),
    ]
