# Generated by Django 5.2.5 on 2025-12-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadPitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pain_points', models.TextField(help_text="Identified gaps like 'No social presence' or 'Slow site'")),
                ('research_summary', models.TextField(blank=True)),
                ('email_subject', models.CharField(blank=True, max_length=255)),
                ('email_body_text', models.TextField(help_text='Professional text-only email')),
                ('email_body_html', models.TextField(help_text='Attractive HTML email template')),
                ('whatsapp_message', models.TextField(help_text='Conversational short message')),
                ('call_script', models.TextField(help_text='Phone script for sales rep')),
            ],
        ),
    ]
