# Generated by Django 5.2.5 on 2025-12-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitch_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadpitch',
            name='image_prompt',
            field=models.TextField(blank=True, help_text='Midjourney/DALL-E prompt with technical camera specs'),
        ),
        migrations.AddField(
            model_name='leadpitch',
            name='video_prompt',
            field=models.TextField(blank=True, help_text='Runway/Luma prompt with camera movement and motion description'),
        ),
        migrations.AddField(
            model_name='leadpitch',
            name='visual_style_guide',
            field=models.TextField(blank=True, help_text="AI's analysis of the brand's likely color palette and aesthetic"),
        ),
    ]
