# Generated by Django 5.2.5 on 2026-08-23 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitch_generator', '0002_leadpitch_image_prompt_leadpitch_video_prompt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leadpitch',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who created this pitch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_pitches', to=settings.AUTH_USER_MODEL),
        ),
    ]
