# Generated by Django 5.2.5 on 2026-02-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='N/A', max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(default='N/A', max_length=255)),
                ('number', models.CharField(blank=True, default='N/A', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
